#+title: Semana 2
#+author: Valentin Vergara
#+date: 2020:Jun:16

#+OPTIONS: toc:nil num:nil date:nil html-postamble:nil
#+LANGUAGE: es

* Previously...
A partir de esta semana, voy a incluir un video donde trate de responder a todas las preguntas que reciba durante la semana. Aún no recibo (de la mayoría) un email con la breve reseña biográfica que les pedí la semana pasada. Por favor, tçomense unos minutos para enviarla, así como también cualquier cosa que no haya quedado clara hasta aquí

#+BEGIN_CENTER 
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/1znnCHOfrZM" frameborder="30" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export
#+END_CENTER

* Bases conceptuales para abordar el Muestreo
Antes de tratar el tema de muestreo, es pertinente tratar las bases conceptuales de probabilidad y distribuciones estadísticas. A partir de ellos podremos seguir avanzando en aplicaciones computacionales.

** Datos
No son exactamente datos, pero sí /proxies/ que sirven para superar algunas limitaciones de SPSS. Revisen los videos, porque ahí explico esto con mayor detalle.

- [[file:data/5k.xlsx][5000 casos]]
- [[file:data/k.xlsx][1000 casos]]

** [[file:docs/week2-1.pdf][Conceptos básicos de probabilidad]]
En este documento se tratan temas que muy probablemente ustedes ya conocen, pero es bueno tenerlos de forma explícita, como consulta. Además, incluyo un video con el desarrollo de algunos ejemplos

** Aplicando conceptos de probabilidad
En el documento de conceptos básicos hay algunos ejemplos no resueltos, que desarrollo en este video.

#+begin_center
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/hRBs9Ok32CQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export
#+end_center

* Diferencias entre población y muestra

** [[file:docs/week2-2.pdf][Población, muestra y error estándar]]
En este documento explico conceptos básicos que utilizaremos para entender la lógica detrás del muestreo. Son además fundamentales para desarrollar la prueba de hipótesis.

** Algunas aplicaciones en SPSS
En este video les muestro cómo es posible aplicar algunos conceptos del documento anterior. Lamentablemente no se escucha muy bien en algunas partes, pero nunca dura más de un minuto. Sugiero bajar la velocidad al video en esos segmentos.

#+begin_center
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/QI_cvOrwzrA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export
#+end_center


--------------- 
