
#+title: Semana 3
#+author: Valentin Vergara

#+OPTIONS: toc:nil num:nil date:nil html-postamble:nil
#+LANGUAGE: es

* Previously...
¿Cómo les fue con la simulación de los puntajes PSU?

*ACTUALIZACIÓN AL 7 DE JULIO*: Esta sección se va a actualizar en la medida que llegue un número importante de preguntas que ameriten crear un video donde las responda. Si no es ese el caso, intentaré responder todas sus preguntas por email.

* [[file:docs/week3-1.pdf][Prueba de hipótesis]]
El esqueleto lógico de todo lo que veremos de aquí en adelante se encuentra en los cuatro pasos de la prueba de hipótesis. En este documento explico los cuatro pasos a partir de un ejemplo muy simple. Luego veremos el detalle de los intervalos de confianza y los valores $p$, donde empezamos a hacer uso del error estándar.

El siguiente video muestra un breve ejemplo (el mismo del documento), que se termina de desarrollar en la siguiente sección.

#+begin_center
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/R7c8H9bUXKE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export
#+end_center
 
* [[file:docs/week3-2.pdf][Intervalos de confianza y valores $p$]] 
En este documento explico de forma más extensiva dos herramientas que vamos a usar de aquí en adelante, cada vez que hagamos una prueba de hipótesis: intervalos de confianza y valores $p$. A partir de un ejemplo simple, les muestro cómo esto se puede usar. Sugiero no preocuparse demasiado del tratamiento matemático (tratenlo de forma tan superficial como lo hago yo en el documento), ya que como muestro en el siguiente video, hay calculadoras o tablas que nos pueden ayudar para esto. El objetivo principal es que quede clara la lógica detrás de estas herramientas.

#+begin_center
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/18xVc5bxonY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export
#+end_center

* [[file:docs/week3-3.pdf][Comparación entre dos grupos]]
En este documento se presenta la distribución $t$ y sus usos cuando no se cuenta con toda la información respecto de la población.

Para seguir los ejemplos del video a continuación, sugiero descargar los siguientes archivos de datos:

- [[https://drive.google.com/file/d/1vh9cxc5048wIuAVfz-6dRNZr1SiO3gLJ/view?usp=sharing][Muestra de la encuesta Casen 2017]]: En este conjunto de datos encontrarán una *muestra* de la encuesta Casen 2017. Es importante aclarar que es una muestra en términos de las columnas, no de las filas. Dicho de otra forma, no son todas las variables que se trabajan en este conjunto de datos, sino que sólo seleccioné algunas variables del módulo de ingresos y todas las variables de los módulos de educación y trabajo.

- [[file:data/beers.csv][Efecto de la cerveza]]: Este conjunto de datos presenta una medición de los errores que comete un grupo de personas al manjear un automóvil. estas mediciones se efectúan antes y después de beber cerveza.

#+begin_center
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/o8EexwxC7eM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export
#+end_center









--------------- 
